POST https://services8.arcgis.com/IJcGtArxG8IPalnE/arcgis/rest/services/SM_Trout_Streams/FeatureServer/0/query?where=Displ_Name='Jacob Fork'&Shape_Leng>13000&outFields=Displ_Name&returnIds=true&f=JSON
